name: Gene Kogan
markdown: kramdown
collections:
  works:
    output: true
    permalink: /works/:path/    
  writings:
    output: true
    permalink: /blog/:path/ 
  pages:
    output: true
    permalink: /:path/